
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JKN_E_SHOP
    username: jon
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false  # Disable auto-commit for handling Large Objects

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true  # Helps with LOB handling in Hibernate

server:
  port: 9091

api:
  prefix: /JKN-Online/api/Shop

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: kyeyunejonathan001@gmail.com
spring.mail.password: lpbp xcaz ydfg wgfr
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
